apiVersion: v1
kind: Pod
metadata:
  name: service1-01
  labels:
    type: frontend
spec:
  restartPolicy: Always
  containers:
  - name: service1
    image: service1:v1
    ports:
      - containerPort: 80

    readinessProbe:
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 2
      httpGet:
        path: /health
        port: 80
        httpHeaders:
          - name: Accept
            value: application/json

    livenessProbe:
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 3
      httpGet:
        path: /alive
        port: 80
        httpHeaders:
          - name: Accept
            value: application/json